[env]
TERM = "xterm-256color"
[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 0.90 

[window.padding]
x = 0
y = 0    

[font.offset]
# This makes nvim and alacritty algined for some reason
x = 1
y = 1

[general]
import = ["~/dotfiles/alacritty/kanagawa_wave.toml"]


[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"
